# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2b660fa485677da44b0443579b339704fef8beae0e5e490e1c2f5a13228ba08fd08e967bb2e56fdc8275827291dcf75b3c629598f08584200378e2de3d8393

test:
  secret_key_base: bd0a47cfe5ce0e57917ea8bab8f310366bea7567f238388694af967efcec50476f4660488cea5bdd6619f764625f23e7df1d5601adc77b618dfda0a29cd7163e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
